### ISSUE TITLE
"Error: Could not encode" when set mode "development"

### ISSUE THREAD

**Issue by qiulang** [socketio/socket.io-admin-ui#48]
I notice I only have dashboard and servers menu
<img width="1039" alt="after login" src="https://user-images.githubusercontent.com/516243/179686005-abe58b3e-4d50-427d-8a65-7252cb9a8c3e.png">

I think this is because start my nodejs using "NODE_ENV=production node index.js" so I set mode code specifically in code  

```
instrument(io, {
  auth: {
     ...
  },
  mode: "development"
});
```

But then server crash with error 

```
Error: Could not encode
 at _encode (/home/express/node_modules/notepack.io/lib/encode.js:256:13)
 at _encode (/home/express/node_modules/notepack.io/lib/encode.js:162:19)
 at _encode (/home/express/node_modules/notepack.io/lib/encode.js:162:19)
 at _encode (/home/express/node_modules/notepack.io/lib/encode.js:246:17)
 at _encode (/home/express/node_modules/notepack.io/lib/encode.js:162:19)
 at Object.encode (/home/express/node_modules/notepack.io/lib/encode.js:261:41)
 at RedisAdapter.broadcast (/home/express/node_modules/socket.io-redis/dist/index.js:313:33)
 at BroadcastOperator.emit (/home/express/node_modules/socket.io/dist/broadcast-operator.js:109:22)
 at Namespace.emit (/home/express/node_modules/socket.io/dist/namespace.js:170:73)
 at Socket.<anonymous> (/home/express/node_modules/@socket.io/admin-ui/dist/index.js:284:36)
```

I searched this error and found someone else also hit this error

https://bestofvue.com/repo/socketio-socket-io-admin-ui-vuejs-web-sockets  (at "7. Error serialising sockets with session stores")

**Comment by qiulang** [comment]
I saw this issue https://github.com/socketio/socket.io-admin-ui/issues/7  was closed at 0.1.2 but I am using 0.4.0 and still hit it.

**Comment by mgarf** [comment]
+1 seeing it myself as well

**Comment by mgarf** [comment]
Here is my stacktrace (similar to above)

<img width="533" alt="image" src="https://user-images.githubusercontent.com/5124393/185706791-fa1692db-7c12-4c45-898b-8e01670d23f3.png">

**Comment by aryaman-titan** [comment]
I'm encountering the same issue

**Comment by darrachequesne** [comment]
I think I have found the culprit, this should be fixed by https://github.com/socketio/socket.io-admin-ui/commit/6d58a755b4d692970d3f2066903a4d503f334f0a.

I'll publish a new version later today.

**Comment by darrachequesne** [comment]
Released in [0.5.1](https://github.com/socketio/socket.io-admin-ui/releases/tag/0.5.1). Thanks for your patience :+1:

**Comment by qiulang** [comment]
@darrachequesne I have updated to 0.5.1 but I still get the same problem,

Before login to https://admin.socket.io/ 

<img width="919" alt="socket & room stats" src="https://user-images.githubusercontent.com/516243/194827816-d8ef55b3-6372-4c41-8770-d39efa9d85b0.png">

But after log in, no socket/room stats

<img width="1286" alt="no socket & room stats" src="https://user-images.githubusercontent.com/516243/194828170-6c89af60-2288-469e-a4da-869baa0828b3.png">

**Comment by qiulang** [comment]
@darrachequesne I have verified 0.5.1 worked and I would like turn it into feature request: is it possible to make mode setting  a runtime setting, so I can turn it on and off when I need ?

I understand the development mode will be a burden to https://admin.socket.io/ but we will host the Admin UI server ourselves so a runtime setting is more appropriate.

**Comment by qiulang** [comment]
@darrachequesne 0.5.1 also fixed the issue I raised here https://github.com/darrachequesne/notepack/issues/29
